package demo.pharma.payment;
import demo.pharma.common.exception.*; import demo.pharma.common.web.PageResponse; import demo.pharma.purchase.*; import demo.pharma.supplier.*; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import lombok.*; import org.springframework.data.domain.*; import org.springframework.data.web.PageableDefault; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.math.*; import java.time.*; import java.util.*;
@RestController @RequiredArgsConstructor public class PaymentController {private final PaymentService service;private final PurchaseInvoiceRepository invoices;private final SupplierPaymentRepository payments;private final SupplierRepository suppliers;private final PurchaseOrderRepository orders;
 record InvoiceRequest(@NotBlank String invoiceNumber,@NotNull LocalDate invoiceDate,@NotNull UUID supplierId,UUID purchaseOrderId,@NotNull @PositiveOrZero BigDecimal subtotal,@PositiveOrZero BigDecimal discount,@PositiveOrZero BigDecimal tax){} record InvoiceView(UUID id,String invoiceNumber,LocalDate invoiceDate,UUID supplierId,UUID purchaseOrderId,BigDecimal total,BigDecimal paid,BigDecimal outstanding,PaymentStatus paymentStatus){} record SupplierPaymentRequest(@NotNull UUID purchaseInvoiceId,@NotNull @Positive BigDecimal amount,@NotNull PaymentMethod paymentMethod,String referenceNumber,String notes){} record SupplierPaymentView(UUID id,UUID invoiceId,UUID supplierId,BigDecimal amount,PaymentMethod paymentMethod,String referenceNumber,LocalDate paymentDate){} record DemoChargeRequest(@NotBlank String referenceType,UUID referenceId,@NotNull @Positive BigDecimal amount,@NotNull PaymentMethod paymentMethod,String notes){} record DemoChargeView(UUID id,DemoPaymentStatus status,String terminalReference,BigDecimal amount,PaymentMethod paymentMethod,String referenceType,UUID referenceId){}
 @GetMapping("/api/purchase-invoices") @PreAuthorize("hasAuthority('PURCHASE_VIEW')") PageResponse<InvoiceView> invoices(@PageableDefault(size=20,sort="invoiceDate",direction=Sort.Direction.DESC)Pageable p){return PageResponse.of(invoices.findAll(p).map(this::iv));}
 @PostMapping("/api/purchase-invoices") @PreAuthorize("hasAuthority('PURCHASE_CREATE')") InvoiceView invoice(@Valid@RequestBody InvoiceRequest r){Supplier s=suppliers.findById(r.supplierId()).orElseThrow(()->new NotFoundException("Supplier",r.supplierId()));PurchaseOrder o=r.purchaseOrderId()==null?null:orders.findById(r.purchaseOrderId()).orElseThrow(()->new NotFoundException("Purchase order",r.purchaseOrderId()));if(o!=null&&!o.getSupplier().getId().equals(s.getId()))throw new BusinessException("Purchase order supplier must match invoice supplier");return iv(service.createInvoice(r.invoiceNumber(),r.invoiceDate(),s,o,r.subtotal(),r.discount(),r.tax()));}
 @GetMapping("/api/purchase-invoices/{id}") @PreAuthorize("hasAuthority('PURCHASE_VIEW')") InvoiceView invoice(@PathVariable UUID id){return iv(find(id));}
 @PostMapping("/api/supplier-payments") @PreAuthorize("hasAuthority('PAYMENT_CREATE')") SupplierPaymentView pay(@Valid@RequestBody SupplierPaymentRequest r){return pv(service.pay(r.purchaseInvoiceId(),r.amount(),r.paymentMethod(),r.referenceNumber(),r.notes()));}
 @GetMapping("/api/supplier-payments") @PreAuthorize("hasAuthority('PAYMENT_VIEW')") PageResponse<SupplierPaymentView> payments(@PageableDefault(size=20,sort="paymentDate",direction=Sort.Direction.DESC)Pageable p){return PageResponse.of(payments.findAll(p).map(this::pv));}
 @PostMapping("/api/payments/demo/charge") @PreAuthorize("hasAuthority('PAYMENT_CREATE')") DemoChargeView demo(@Valid@RequestBody DemoChargeRequest r){DemoPaymentTransaction t=service.charge(r.referenceType(),r.referenceId(),r.amount(),r.paymentMethod(),r.notes());return new DemoChargeView(t.getId(),t.getStatus(),t.getTerminalReference(),t.getAmount(),t.getPaymentMethod(),t.getReferenceType(),t.getReferenceId());}
 private PurchaseInvoice find(UUID id){return invoices.findById(id).orElseThrow(()->new NotFoundException("Purchase invoice",id));}private InvoiceView iv(PurchaseInvoice i){BigDecimal paid=payments.totalPaid(i.getId());return new InvoiceView(i.getId(),i.getInvoiceNumber(),i.getInvoiceDate(),i.getSupplier().getId(),i.getPurchaseOrder()==null?null:i.getPurchaseOrder().getId(),i.getTotal(),paid,i.getTotal().subtract(paid),i.getPaymentStatus());}private SupplierPaymentView pv(SupplierPayment p){return new SupplierPaymentView(p.getId(),p.getPurchaseInvoice().getId(),p.getSupplier().getId(),p.getAmount(),p.getPaymentMethod(),p.getReferenceNumber(),p.getPaymentDate());}}
